 version: 2.1
 executors:
   test:
      environment:
        PROJECT_NAME: projet1_ade
        GITHUB_USER: redwappin
      docker:
        - image: circleci/buildpack-deps:trusty
 jobs:
   build:
     executor: test 
     steps:
       - checkout
       - run: echo "A first hello"
       - run:
          name: Build
          command: docker-compose -f ./docker-compose.yml build