 version: 2.1
 executors:
   test:
      docker:
        - image: circleci/buildpack-deps:trusty
 jobs:
   build:
     executor: test 
     steps:
       - checkout
       - setup_remote_docker # This environment is remote, fully-isolated and has been configured to execute Docker commands
       - run:
          name: Build docker image
          command: docker-compose -f ./docker-compose.yml build --compress --force-rm --no-cache --pull --parallel
       - run:
          name: Take a look to docker images
          command: docker images -a
      
      