 version: 2.1
 executors:
   publisher:
      working_directory: ~/project
      environment:
        IMAGE_NAME: redwappin/projet1_ade
      docker:
        - image: circleci/buildpack-deps:trusty
 jobs:
   install:
     executor: publisher 
     steps:
       - checkout
       - setup_remote_docker # This environment is remote, fully-isolated and has been configured to execute Docker commands
       - run:
          name: Build docker image
          command: docker-compose -f ./docker-compose.yml build --compress --force-rm --no-cache --pull --parallel
       - run:
          name: Take a look to docker images
          command: docker images -a
       - run:
          name: Archive Docker image
          command: docker save -o ./${PROJECT_NAME}_test.tar project_api
       - persist_to_workspace:
          root: .
          paths:
            - ./*.tar
   test:
     executor: publisher 
     steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy node_modules
          command: cp -r /tmp/workspace/node_modules ./node_modules # Copy node_modules in app folder
       - run:
          name: Run Unit tests
          command: npm test
   publish-tag:
      executor: publisher 
      steps:
        - checkout
        - setup_remote_docker
        - attach_workspace:
            at: /tmp/workspace
        - run:
           name: Load archived Docker image
           command: docker load -i /tmp/workspace/${PROJECT_NAME}_test.tar
        - run:
           name: What is circle tag?
           command: echo $(.circleci/scripts/get_tag.sh)
        - run:
           name: Publish Docker Image to Docker Hub
           command: .circleci/scripts/docker_tag_push.sh

 workflows:
  version: 2
  build-master:
    jobs:
      - install:
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
      - test:
          requires:
            - install
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
      - publish-tag:
          requires:
            - test
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
      