 version: 2.1
 executors:
   test:
      docker:
        - image: circleci/buildpack-deps:trusty
 jobs:
   build:
     executor: test 
     steps:
       - checkout
       - setup_remote_docker # This environment is remote, fully-isolated and has been configured to execute Docker commands
       - run:
          name: Build docker image
          command: docker-compose -f ./docker-compose.yml build --compress --force-rm --no-cache --pull --parallel
       - run:
          name: Take a look to docker images
          command: docker images -a
       - run:
          name: Archive Docker image
          command: docker save -o ${PROJECT_NAME}.tar projet_docker
       - persist_to_workspace:
          root: .
          paths:
            - ./*.tar
    # publish-latest:
    #   executor: test 
    #   steps:
    #     - setup_remote_docker
    #     - run:
    #         name: Publish Docker Image to Docker Hub
    #         command: |
    #           echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    #           docker push $IMAGE_NAME:latest
      
      