FROM node:10

# Create app directory
WORKDIR /home/api/ade

RUN mkdir -p /home/api/ade
 
COPY package.json /home/api/ade

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . /home/api/ade

EXPOSE 3000
CMD [ "node", "server.js" ]